spring:
  h2:
    console.enabled: true
  datasource:
    #url: jdbc:h2:mem:5a220b42-43e8-4c84-ba4b-6b545b456b8c
    url: jdbc:h2:mem:test_mem
  jpa:
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: #johndoe
    password: #dummypassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

customer:
  notification:
    expression: 0 0 12 * * ? #every 12noon


app:
#  jwt-secret: eventsecret note: I used the hashed string as a best practice
  jwt-secret: d8169aa741b827bf8a97bd70ea7c51766ad4d90b356f0f493c716192d36e48e2
  jwt-expiration-milliseconds: 604800000

