INSERT INTO EVENT (ID, EVENT_NAME,EVENT_DESCRIPTION,CATEGORY,ATTENDEE_COUNT,EVENT_DATE) VALUES (1, 'Niyi birthday','CEO Birthday','0',10,'2024-01-28 14:34:00');
INSERT INTO EVENT (ID, EVENT_NAME,EVENT_DESCRIPTION,CATEGORY,ATTENDEE_COUNT,EVENT_DATE) VALUES (2, 'Opening Ceremony','Afcon first match','2',50,'2024-01-24 14:34:00');
INSERT INTO EVENT (ID, EVENT_NAME,EVENT_DESCRIPTION,CATEGORY,ATTENDEE_COUNT,EVENT_DATE) VALUES (3, 'Project launch','Company event','0',20,'2024-01-25 14:34:00');
INSERT INTO EVENT (ID, EVENT_NAME,EVENT_DESCRIPTION,CATEGORY,ATTENDEE_COUNT,EVENT_DATE) VALUES (4, 'Challenge day','Fifa Challenge','2',12,'2024-01-26 14:34:00');
INSERT INTO EVENT (ID, EVENT_NAME,EVENT_DESCRIPTION,CATEGORY,ATTENDEE_COUNT,EVENT_DATE) VALUES (5, 'Abel birthday','Java Dev Birthday','0',5,'2024-01-26 14:34:00');

INSERT INTO USERR (ID, namee, EMAIL,PASSWORD) VALUES (1,'Abel', 'Abel@gmail.com','$2a$10$Kco5ugvTQGGEtgv6E/OYIu0DMgjQ6zXWxoq9GQMrKYEgb7SJ/3Vxq');
INSERT INTO USERR (ID, namee, EMAIL,PASSWORD) VALUES (2,'Admin', 'Admin@gmail.com','$2a$10$DmSUsQ5usyB2JZNKpDdL6.uuTGmPqadmEqzUvF4hbWEVL1LDpGlXW');

INSERT INTO roles (ID, namee) VALUES (1, 'ROLE_USER');
INSERT INTO roles (ID, namee) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (2, 2);

